#!/bin/bash
PATHTODATA="data/graphsPageRank"

for file in $(ls $PATHTODATA); do
    for id in $(seq 1 3); do
        echo "starting scripts/execPig $PATHTODATA/$file $id"
        scripts/execPig "$PATHTODATA/$file" "$id"
    done
done
